#!/usr/bin/env python3
"""Merge .plan/slices/*.json into .plan/INDEX.md, .plan/WORKSTREAMS.md and .plan/plan.json.

Re-run after any slice file changes:  python3 .plan/_manifests/aggregate.py
"""
import csv, glob, json, os, sys
from collections import Counter, defaultdict

PLAN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEVELS = ["critical", "high", "medium", "low", "info"]
VERDICTS = ["CONFIRMED", "PARTIAL", "DUPLICATE", "ALREADY-FIXED", "INVALID", "WONTFIX-CANDIDATE"]
EFFORT_H = {"S": 1, "M": 4, "L": 12, "XL": 32}

def key_of(issue_file):
    """IDs collide across auditors (AH-, ESS-, SMS-, TS-), so the issue file stem is the unique key."""
    return os.path.basename(str(issue_file or "")).removesuffix(".md")

manifest_ids = {}
for m in sorted(glob.glob(os.path.join(PLAN, "_manifests", "*.tsv"))):
    slice_ = os.path.basename(m)[:-4]
    with open(m) as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            manifest_ids[key_of(row["issue_file"])] = slice_

issues, workstreams, problems = {}, defaultdict(lambda: {"ids": [], "slices": set(), "titles": set(), "deps": set(), "effort": []}), []
for f in sorted(glob.glob(os.path.join(PLAN, "slices", "*.json"))):
    slice_ = os.path.basename(f)[:-5]
    try:
        data = json.load(open(f))
    except Exception as e:  # noqa: BLE001
        problems.append(f"{slice_}: invalid JSON ({e})")
        continue
    for it in data.get("issues", []):
        it["_slice"] = slice_
        k = key_of(it.get("issue_file")) or it["id"]
        it["_key"] = k
        if k in issues:
            problems.append(f"{k} appears in both {issues[k]['_slice']} and {slice_}")
        issues[k] = it
    for w in data.get("workstreams", []):
        ws = workstreams[w["slug"]]
        ws["slices"].add(slice_)
        ws["titles"].add(w.get("title", w["slug"]))
        ws["ids"].extend(w.get("ids", []))
        ws["deps"].update(w.get("depends_on_workstreams", []) or [])
        ws["effort"].append(w.get("effort"))

missing = sorted(set(manifest_ids) - set(issues))
extra = sorted(set(issues) - set(manifest_ids))
if missing:
    problems.append(f"{len(missing)} manifest IDs missing from slice outputs: {', '.join(missing)}")
if extra:
    problems.append(f"{len(extra)} IDs in outputs not in any manifest: {', '.join(extra)}")

# resolve bare IDs in workstream lists to unique keys (ambiguous IDs resolve within the same slice)
by_id = defaultdict(list)
for k, it in issues.items():
    by_id[it["id"]].append(k)
for slug, w in workstreams.items():
    resolved = []
    for ref in w["ids"]:
        if ref in issues:
            resolved.append(ref)
        elif len(by_id.get(ref, [])) == 1:
            resolved.append(by_id[ref][0])
        else:
            cands = [k for k in by_id.get(ref, []) if issues[k]["_slice"] in w["slices"]]
            resolved.extend(cands[:1] or [ref])
    w["ids"] = resolved

def label(k):
    it = issues.get(k)
    if not it:
        return k
    return k if len(by_id[it["id"]]) > 1 else it["id"]

# attach issues that name a workstream the slice-level list forgot
for iid, it in issues.items():
    slug = it.get("workstream")
    if slug and iid not in workstreams[slug]["ids"]:
        workstreams[slug]["ids"].append(iid)
        workstreams[slug]["slices"].add(it["_slice"])

def lvl(i):
    return LEVELS.index(i.get("level", "info")) if i.get("level") in LEVELS else 9

def ws_rank(slug):
    ids = [issues[i] for i in workstreams[slug]["ids"] if i in issues]
    active = [i for i in ids if i.get("verdict") in ("CONFIRMED", "PARTIAL")]
    top = min((lvl(i) for i in active), default=9)
    sec = sum(1 for i in active if i.get("category") == "security")
    return (top, -sec, -len(active), slug)

# ---------- INDEX.md ----------
vc = Counter(i.get("verdict") for i in issues.values())
by = defaultdict(Counter)
for i in issues.values():
    by[i.get("level")][i.get("verdict")] += 1
out = ["# Issue index — validation verdicts\n",
       f"Generated by `.plan/_manifests/aggregate.py` from `.plan/slices/*.json`. {len(issues)} of {len(manifest_ids)} open issues validated.\n",
       "## Verdicts × level\n", "| Level | " + " | ".join(VERDICTS) + " | Total |", "|---|" + "---|" * (len(VERDICTS) + 1)]
for L in LEVELS:
    if by[L]:
        out.append(f"| {L} | " + " | ".join(str(by[L][v]) for v in VERDICTS) + f" | {sum(by[L].values())} |")
out.append("| **total** | " + " | ".join(f"**{vc[v]}**" for v in VERDICTS) + f" | **{len(issues)}** |\n")
if problems:
    out.append("## Aggregation warnings\n")
    out += [f"- {p}" for p in problems] + [""]
rs = Counter(i.get("recommended_status") for i in issues.values())
out.append("## Recommended status after validation\n")
out += [f"- `{k}`: {v}" for k, v in rs.most_common()] + [""]
out.append("## All issues\n")
out.append("| ID | Level | Cat | Verdict | Conf | Workstream | Effort | → Status | Slice | Title |")
out.append("|---|---|---|---|---|---|---|---|---|---|")
for i in sorted(issues.values(), key=lambda i: (lvl(i), i.get("workstream") or "~", i["_key"])):
    fx = i.get("fix") or {}
    dup = f" → {i['duplicate_of']}" if i.get("duplicate_of") else ""
    out.append(f"| [{label(i['_key'])}](../{i.get('issue_file','')}) | {i.get('level')} | {i.get('category','')} | {i.get('verdict')}{dup} | {i.get('confidence','')} | "
               f"{i.get('workstream') or '—'} | {fx.get('effort','') if isinstance(fx, dict) else ''} | {i.get('recommended_status','')} | "
               f"[{i['_slice']}](slices/{i['_slice']}.md) | {str(i.get('title','')).replace('|','/')[:100]} |")
open(os.path.join(PLAN, "INDEX.md"), "w").write("\n".join(out) + "\n")

# ---------- WORKSTREAMS.md ----------
out = ["# Workstreams — merged across slices\n",
       "Ranked by highest open severity, then security weight, then size. Effort is the sum of per-issue estimates "
       "(S=1h, M=4h, L=12h, XL=32h) for CONFIRMED/PARTIAL issues and is an upper bound — grouped fixes overlap.\n",
       "| # | Workstream | Slices | Open (C/P) | Top level | Security | Est. hours | Depends on | IDs |", "|---|---|---|---|---|---|---|---|---|"]
wsj = []
for n, slug in enumerate(sorted(workstreams, key=ws_rank), 1):
    w = workstreams[slug]
    ids = sorted(set(w["ids"]), key=lambda x: (lvl(issues.get(x, {})), x))
    active = [issues[i] for i in ids if i in issues and issues[i].get("verdict") in ("CONFIRMED", "PARTIAL")]
    hours = sum(EFFORT_H.get(((i.get("fix") or {}).get("effort") or "M"), 4) for i in active)
    top = LEVELS[min((lvl(i) for i in active), default=4)] if active else "—"
    sec = sum(1 for i in active if i.get("category") == "security")
    out.append(f"| {n} | `{slug}` | {', '.join(sorted(w['slices']))} | {len(active)} | {top} | {sec} | {hours} | "
               f"{', '.join(sorted(w['deps'])) or '—'} | {', '.join(label(i) for i in ids)} |")
    wsj.append({"rank": n, "slug": slug, "titles": sorted(w["titles"]), "slices": sorted(w["slices"]), "ids": ids,
                "open": len(active), "top_level": top, "security": sec, "est_hours": hours, "depends_on": sorted(w["deps"])})
open(os.path.join(PLAN, "WORKSTREAMS.md"), "w").write("\n".join(out) + "\n")

json.dump({"issues": sorted(issues.values(), key=lambda i: i["_key"]), "workstreams": wsj, "warnings": problems},
          open(os.path.join(PLAN, "plan.json"), "w"), indent=1, default=list)
print(f"issues={len(issues)}/{len(manifest_ids)} workstreams={len(workstreams)} verdicts={dict(vc)}")
for p in problems:
    print("WARN", p, file=sys.stderr)

# ---------- programs/ + DECISIONS.md ----------
import re as _re
PROG = json.load(open(os.path.join(PLAN, "_manifests", "programs.json")))["programs"]
slug2prog = {s: p["key"] for p in PROG for s in p["slugs"]}
unmapped = sorted(s for s in workstreams if s not in slug2prog and any(
    issues.get(i, {}).get("verdict") in ("CONFIRMED", "PARTIAL") for i in workstreams[s]["ids"]))
if unmapped:
    print("WARN unmapped active workstreams:", ", ".join(unmapped), file=sys.stderr)
ACTIVE = ("CONFIRMED", "PARTIAL")
os.makedirs(os.path.join(PLAN, "programs"), exist_ok=True)
for old in glob.glob(os.path.join(PLAN, "programs", "*.md")):
    os.remove(old)

def fname(p):
    return f"{p['key']}-" + _re.sub(r"[^a-z0-9]+", "-", p["title"].lower()).strip("-") + ".md"

def anchor(i):
    return f"slices/{i['_slice']}.md"

def dossier_link(i):
    return f"[{label(i['_key'])}](../{anchor(i)})"

prog_rows = []
for p in PROG:
    pinned = p.get("first", [])
    slugs = [s for s in sorted(workstreams, key=lambda s: (pinned.index(s) if s in pinned else len(pinned), ws_rank(s))) if slug2prog.get(s) == p["key"]]
    ids = [k for s in slugs for k in dict.fromkeys(workstreams[s]["ids"]) if k in issues]
    act = [issues[k] for k in dict.fromkeys(ids) if issues[k]["verdict"] in ACTIVE]
    closed = [issues[k] for k in dict.fromkeys(ids) if issues[k]["verdict"] not in ACTIVE]
    hours = sum(EFFORT_H.get(((i.get("fix") or {}).get("effort") or "M"), 4) for i in act)
    lv = Counter(i["level"] for i in act)
    dec = [i for i in act if i.get("needs_decision")]
    prog_rows.append((p, len(act), len(closed), hours, lv, len(dec)))
    o = [f"# {p['key']} — {p['title']}\n",
         f"Phase {p['phase']} · {len(act)} open issues to fix (" + ", ".join(f"{lv[l]} {l}" for l in LEVELS if lv[l]) + f") · {len(closed)} closed by validation · "
         f"~{hours}h summed per-issue estimate (upper bound) · {len(dec)} need a decision first.\n",
         "Each issue below links to its full dossier (evidence at HEAD `ec065a7`, fix steps, tests, acceptance) in its slice file. "
         "Work workstream by workstream, top to bottom; within a workstream do the canonical issue first — its fix closes the listed duplicates.\n"]
    for s in slugs:
        w = workstreams[s]
        wids = [k for k in dict.fromkeys(w["ids"]) if k in issues]
        wact = [issues[k] for k in wids if issues[k]["verdict"] in ACTIVE]
        if not wact:
            continue
        wh = sum(EFFORT_H.get(((i.get("fix") or {}).get("effort") or "M"), 4) for i in wact)
        o.append(f"## `{s}` — {' / '.join(sorted(w['titles']))}\n")
        o.append(f"Slices: {', '.join(f'[{x}](../slices/{x}.md)' for x in sorted(w['slices']))} · ~{wh}h" +
                 (f" · depends on workstreams: {', '.join(f'`{d}`' for d in sorted(w['deps']))}" if w["deps"] else "") + "\n")
        o.append("| Issue | Level | Cat | Verdict | Effort | Blocked by | Fix summary |")
        o.append("|---|---|---|---|---|---|---|")
        for i in sorted(wact, key=lambda i: (lvl(i), i["_key"])):
            fx = i.get("fix") or {}
            dep = ", ".join(i.get("depends_on") or []) or "—"
            flag = " ⚖️ decision" if i.get("needs_decision") else ""
            o.append(f"| {dossier_link(i)} | {i['level']} | {i.get('category','')} | {i['verdict']}{flag} | {fx.get('effort','')} | {dep} | "
                     f"{str(fx.get('summary','')).replace('|','/').replace(chr(10),' ')} |")
        dups = [issues[k] for k in wids if issues[k]["verdict"] not in ACTIVE]
        if dups:
            o.append("\nClosed by validation in this workstream: " + ", ".join(
                f"{label(i['_key'])} ({i['verdict']}{' → ' + str(i['duplicate_of']) if i.get('duplicate_of') else ''})" for i in dups))
        o.append("")
    open(os.path.join(PLAN, "programs", fname(p)), "w").write("\n".join(o) + "\n")

# program summary appended to WORKSTREAMS.md
with open(os.path.join(PLAN, "WORKSTREAMS.md"), "a") as fh:
    fh.write("\n# Programs (roll-up)\n\n| Program | Phase | Open | high | medium | low | info | Decisions | Est. hours |\n|---|---|---|---|---|---|---|---|---|\n")
    for p, na, nc, h, lv, nd in prog_rows:
        fh.write(f"| [{p['key']} {p['title']}](programs/{fname(p)}) | {p['phase']} | {na} | {lv['high']} | {lv['medium']} | {lv['low']} | {lv['info']} | {nd} | {h} |\n")
json.dump([{"key": p["key"], "phase": p["phase"], "title": p["title"], "file": "programs/" + fname(p), "open": na, "closed": nc,
            "est_hours": h, "levels": dict(lv), "decisions": nd} for p, na, nc, h, lv, nd in prog_rows],
          open(os.path.join(PLAN, "_manifests", "programs.rollup.json"), "w"), indent=1)

# DECISIONS.md
dec = sorted((i for i in issues.values() if i.get("needs_decision")), key=lambda i: (slug2prog.get(i.get("workstream"), "P99"), lvl(i), i["_key"]))
o = ["# Decision register\n",
     f"{len(dec)} validated issues need a product/design call before implementation (recommended status `ready-for-human`). "
     "Each carries the options the validator found and a recommendation shaped by the standing preferences "
     "(type-system-first, flexibility over complexity, no API-stability arguments, no `as`). "
     "Answer by editing the issue file's Comments with `Decision (date): …` and flipping it to `ready-for-agent`.\n"]
cur = None
for i in dec:
    pk = slug2prog.get(i.get("workstream"), "—")
    if pk != cur:
        cur = pk
        t = next((p["title"] for p in PROG if p["key"] == pk), "Unassigned")
        o.append(f"\n## {pk} — {t}\n")
    o.append(f"### {label(i['_key'])} — {i.get('title','')}\n")
    o.append(f"{i['level']} · {i.get('category','')} · workstream `{i.get('workstream')}` · dossier: {dossier_link(i).replace('](../', '](')}\n")
    for opt in (i.get("decision_options") or []):
        o.append(f"- {opt}")
    o.append(f"\n**Recommendation:** {i.get('recommendation') or '—'}\n")
open(os.path.join(PLAN, "DECISIONS.md"), "w").write("\n".join(o) + "\n")
print(f"programs={len(PROG)} decisions={len(dec)}")
