#!/usr/bin/env python3
"""
One-time rebrand: effect-auth -> Awthaq.

Why: the npm scope `@effect-auth/*` was already taken by an abandoned,
unrelated alpha package (documented back in `research/01-effect-ecosystem.md`
and `archive/PRD.md` 1.1 as a known open decision from day one). This script
renames the project's own npm scope, env var prefix, error-message prefix,
and brand prose from "effect-auth"/"Effect-Auth"/"EffectAuth" to
"awthaq"/"Awthaq" everywhere it refers to THIS project.

It deliberately does NOT touch:
  - .scratch/**            historical planning record, frozen as written
  - pnpm-lock.yaml          regenerated by `pnpm install` instead of text-patched
  - upstream-comparison-dashboard.html   pre-existing untracked scratch output,
                            heavily about the *unrelated* EduSantosBrito/effect-auth
                            repo; out of scope for this rename entirely
  - the spec/ BEH-EA-*/ADR-EA-*/REQ-EA-*/URS-EA-*/EFAUTH-* identifier
    namespace: internal traceability IDs wired into
    spec/scripts/verify-traceability.sh, unrelated to the npm-name collision
    this rename actually solves. Renaming them is a separate, much
    higher-risk refactor with no benefit here (nobody types these into npm).

Known landmines (real, external things that also contain the substring
"effect-auth" and must NOT be renamed):
  - `EduSantosBrito/effect-auth` (a real, unrelated GitHub repo) -- only
    appears in .scratch/ and the untracked dashboard html, both already
    excluded above, so no special handling needed here.
  - `@kndwin/effect-auth` / `kndwin/effect-auth` / `nr1brolyfan/effect-auth`
    (real, unrelated third-party npm packages/repos, cited as prior art in
    research/01-effect-ecosystem.md) -- protected via placeholder swap.
  - A third real thing: an abandoned alpha package literally published at
    `@effect-auth/core` + `@effect-auth/cli` (not ours -- see
    research/01-effect-ecosystem.md's own "Prior art is immature" bullet).
    Every sentence *reporting that this package existed and that the scope
    was taken* is a historical research finding and must stay describing
    the OLD name, not the new one -- see HISTORICAL_FACTS below. Everywhere
    else in the same files (design recommendations for THIS project's own
    naming, e.g. `"@effect-auth/password/PasswordService"` as an illustrative
    tag-id) is a normal rename.

Run from the repo root:
    python3 .scratch/rename-to-awthaq/rename.py
Then verify with `pnpm check`.
"""

import subprocess
import sys

ROOT = subprocess.run(
    ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
).stdout.strip()

EXCLUDE_EXACT = {"pnpm-lock.yaml"}
EXCLUDE_PREFIX = (".scratch/",)
SPECIAL_LANDMINE_FILE = "research/01-effect-ecosystem.md"

# Order matters: longer/more specific patterns first.
REPLACEMENTS = [
    ("@effect-auth/", "@awthaq/"),
    ("EFFECT_AUTH_", "AWTHAQ_"),
    ("Effect-auth", "Awthaq"),
    ("Effect Auth", "Awthaq"),
    ("Effect auth", "Awthaq"),
    ("EffectAuth", "Awthaq"),
    ("effect-auth", "awthaq"),
]

# Real external repos/packages that share the "effect-auth" substring by
# coincidence, protected during the generic pass in SPECIAL_LANDMINE_FILE.
EXTERNAL_REPO_PLACEHOLDERS = {
    "@kndwin/effect-auth": "@@PLACEHOLDER_KNDWIN_SCOPED@@",
    "kndwin/effect-auth": "@@PLACEHOLDER_KNDWIN@@",
    "nr1brolyfan/effect-auth": "@@PLACEHOLDER_NR1BROLYFAN@@",
}

# Sentences that report a *historical fact about the old name* (the
# abandoned third-party `@effect-auth/core`/`@effect-auth/cli` package, and
# the resulting "scope already taken" finding/decision). These must keep
# saying "effect-auth" -- rewriting them to "awthaq" would turn a true,
# load-bearing research finding into a false claim about the new name.
# Each entry: (file, corrupted-text-after-generic-pass, restored-text).
HISTORICAL_FACTS = [
    (
        "research/01-effect-ecosystem.md",
        "- **Prior art is immature**: `@awthaq/core` + `@awthaq/cli` (alpha, 18 versions, "
        "last publish 2026-07-29, GitHub repo now 404) and `@kndwin/effect-auth` "
        "(2026-08-31, brand new) exist; the dominant community pattern is "
        "**better-auth wrapped in Effect** (multiple starters). "
        "**The `@awthaq/*` npm namespace is already taken** — the PRD's own "
        'fallback clause ("subject to npm availability") will trigger.',
        "- **Prior art is immature**: `@effect-auth/core` + `@effect-auth/cli` (alpha, 18 "
        "versions, last publish 2026-07-29, GitHub repo now 404) and `@kndwin/effect-auth` "
        "(2026-08-31, brand new) exist; the dominant community pattern is "
        "**better-auth wrapped in Effect** (multiple starters). "
        "**The `@effect-auth/*` npm namespace is already taken** — the PRD's own "
        'fallback clause ("subject to npm availability") will trigger.',
    ),
    (
        "research/README.md",
        "- **npm scope:** `@awthaq/core` and `@awthaq/cli` already exist on npm "
        "(alpha, dead repo). Naming decision required before MVP. (01)",
        "- **npm scope:** `@effect-auth/core` and `@effect-auth/cli` already exist on npm "
        "(alpha, dead repo). Naming decision required before MVP. (01) "
        "*(Resolved: renamed to Awthaq, npm scope `@awthaq/*`.)*",
    ),
    (
        "archive/PRD.md",
        "**Effect Native Auth**. Working npm scope `@awthaq/*`. The scope is already "
        "taken on npm by an abandoned alpha (research 01); a rename is a pending "
        "decision and every example below treats the scope as a placeholder.",
        "**Effect Native Auth**. Working npm scope `@effect-auth/*`. The scope is already "
        "taken on npm by an abandoned alpha (research 01); a rename is a pending "
        "decision and every example below treats the scope as a placeholder. "
        "*(Resolved, post-archival: renamed to Awthaq, npm scope `@awthaq/*`.)*",
    ),
    (
        "archive/design/api-design.md",
        "The `@awthaq/*` scope is a placeholder; it is taken on npm (research 01) "
        "and the rename is a pending decision.",
        "The `@effect-auth/*` scope is a placeholder; it is taken on npm (research 01) "
        "and the rename is a pending decision. "
        "*(Resolved, post-archival: renamed to Awthaq, npm scope `@awthaq/*`.)*",
    ),
]

# Underscore-form literal values (Postgres identifiers can't use hyphens),
# not covered by the hyphenated REPLACEMENTS list above.
UNDERSCORE_FILES = [
    ".github/workflows/check.yml",
    "README.md",
    "research/08-authorization.md",
]
UNDERSCORE_REPLACEMENTS = [
    ("effect_auth_test", "awthaq_test"),
    ("effect_auth", "awthaq"),
]

# The display/marketing title (README H1 + intro) -- not a literal "effect-auth"
# token so the generic pass never touches it; rewritten deliberately here.
README_TITLE_OLD = "# Effect Native Auth\n\nAn authentication runtime for TypeScript, built natively on Effect v4, with authorization delegated to the sibling library [qadi](../qadi)."
README_TITLE_NEW = (
    "# Awthaq\n\n"
    "*Effect Native Auth* — an authentication runtime for TypeScript, built natively on "
    "Effect v4, with authorization delegated to the sibling library [qadi](../qadi). "
    "The name comes from Arabic أوثق (*awthaq*, \"most trustworthy/reliable\") — the "
    "original working name, `effect-auth`, was already taken on npm by an abandoned "
    "package (see `research/01-effect-ecosystem.md`)."
)


def apply_generic(text: str) -> str:
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    return text


def main() -> None:
    files = subprocess.run(
        ["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.splitlines()

    changed = []
    for f in files:
        if f in EXCLUDE_EXACT or f == SPECIAL_LANDMINE_FILE:
            continue
        if any(f.startswith(p) for p in EXCLUDE_PREFIX):
            continue
        path = f"{ROOT}/{f}"
        try:
            with open(path, "r", encoding="utf-8") as fh:
                content = fh.read()
        except (UnicodeDecodeError, IsADirectoryError):
            continue
        if not any(tok in content for tok in ("effect-auth", "EFFECT_AUTH", "EffectAuth")):
            continue
        new_content = apply_generic(content)
        if new_content != content:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_content)
            changed.append(f)

    print(f"Generic rename applied to {len(changed)} files")

    # The one file with real external-repo landmines to protect.
    special_path = f"{ROOT}/{SPECIAL_LANDMINE_FILE}"
    with open(special_path, "r", encoding="utf-8") as fh:
        content = fh.read()
    for real, placeholder in EXTERNAL_REPO_PLACEHOLDERS.items():
        content = content.replace(real, placeholder)
    content = apply_generic(content)
    for real, placeholder in EXTERNAL_REPO_PLACEHOLDERS.items():
        content = content.replace(placeholder, real)
    with open(special_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"Handled landmine file: {SPECIAL_LANDMINE_FILE}")

    # Restore historical facts the generic pass would otherwise corrupt.
    for file, corrupted, restored in HISTORICAL_FACTS:
        path = f"{ROOT}/{file}"
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
        count = content.count(corrupted)
        if count != 1:
            print(
                f"ERROR: expected exactly 1 match restoring historical fact in {file}, found {count}",
                file=sys.stderr,
            )
            sys.exit(1)
        content = content.replace(corrupted, restored)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"Restored historical fact in {file}")

    # Underscore-form literal values.
    for file in UNDERSCORE_FILES:
        path = f"{ROOT}/{file}"
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
        new_content = content
        for old, new in UNDERSCORE_REPLACEMENTS:
            new_content = new_content.replace(old, new)
        if new_content != content:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_content)
            print(f"Applied underscore-form rename in {file}")

    # README display title.
    readme_path = f"{ROOT}/README.md"
    with open(readme_path, "r", encoding="utf-8") as fh:
        content = fh.read()
    if README_TITLE_OLD not in content:
        print("ERROR: README title marker not found -- was it already rewritten?", file=sys.stderr)
        sys.exit(1)
    content = content.replace(README_TITLE_OLD, README_TITLE_NEW)
    with open(readme_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print("Rewrote README title")

    print("\nDone. Now run:\n  pnpm install   # regenerate pnpm-lock.yaml for the new package names\n  pnpm format    # fix line-wrapping shifted by shorter/longer tokens\n  pnpm check     # full verification gate")


if __name__ == "__main__":
    main()
